GET http://localhost:3059/quotes

###
GET http://localhost:3059/quotes/fill

###
POST http://localhost:3059/quotes
Content-Type: application/json

{
    "gallons": 720,
    "deliveryDate": "2015-03-25",
    "address": "101 Main Street",
    "price": 4,
    "due": 8
}

###
GET http://localhost:3059/login

###
POST http://localhost:3059/login
Content-Type: application/json

{
    "username": "werty",
    "password": "werty"
}

###
GET http://localhost:3059/register

###
POST http://localhost:3059/register
Content-Type: application/json

{
    "username": "esxrdc",
    "password": "123d45g67y8",
    "confirmPassword": "123d45g67y8"
}

###
GET http://localhost:3059/profile/fill

###
POST http://localhost:3059/profile
Content-Type: application/json

{
    "name": "kyle",
    "city":"houston",
    "region":"tx",
    "zipcode":"77002",
    "address1": "101 main street",
    "address2": "101 main street"
}